config/routes.rb
Rails.application.routes.draw do
  get     "login"    => "session#new"
  post    "login"    => "session#create"
  delete  "logout"   => "session#destroy"

  resources :posts
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, :content, presence: true
	validates :content, length: { minimum: 100 }
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionHelper  
    before_action :require_login

    def require_login
      unless logged_in?
        redirect_to login_path
      end
    end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
    @posts = Post.all		
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
      flash[:success] = "create post success" 
    else
      render :new 
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post
      flash[:success] = "update post success" 
    else
      render :edit 
    end
  end

  def destroy
    @post.destroy
      redirect_to posts_url
      flash[:success] = "Post was successfully destroyed" 
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
skip_before_action :require_login, only: [:new, :create]	
  def new
  end
  def create
    user = User.find_by name: params[:session][:name].downcase
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Login success"
      log_in user
      redirect_to user
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end  	
  end

  def destroy
    log_out
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = "Register success"
      redirect_to users_path
    else
      flash[:success] = "Register failed"
      render :new
    end
  end

  def show
    @user = User.find_by id: params[:id]
  end  

  private
  def user_params
    params.require(:user).permit :name, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_in user
    session[:user_id] = user.id
  end
  def log_out
    session.delete :user_id
  end
  # GET current_user 
  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  # Check user has logged in before ? 
  def logged_in?
    current_user.present?
  end    	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="jumbotron jumbotron-fluid text-center">
  <div class="container">
    <h1 class="display-4">Welcome to MyBlog</h1>
  </div>
</div>

<div class="row">
	<% @posts.each do |post| %>
		<div class="col-lg-4 col-sm-12 col-md-6 mt-3">
			<h1>
				<%= post.title %>
			</h1>
			<p class="mb-0">
				<%= truncate(post.content, length: 140) %>
			</p>
			<%= link_to 'Read more', post_path(post) %>
		</div>
	<% end %>	
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center">
	<div class="footer1">
		MyBlog 2019
	</div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
  <div class="container">
    <a class="navbar-brand" href="<%= root_path %>">MyBlog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
         <li class="nav-item active">
           <a class="nav-link" href="<%= root_path %>">Home</a>
         </li>
         <li class="nav-item">
           <a class="nav-link" href="/posts">Post Management</a>
         </li>        
         <li class="nav-item">
           <a class="nav-link" href="/posts/new">New Post</a>
         </li>        
         <li class="nav-item">
           <%= link_to "Logout", logout_path, class: "nav-link", method: :delete %> 
         </li>  
      </ul>
    </div>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <%= render 'layouts/nav' %>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>      
  	<div class="container">
	    <%= yield %>
  	</div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", rows: 15 %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th width="25%">Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Return home', root_path %>

app/views/session/new.html.erb
<h1 class="text-center">Login</h1>
<%= form_for :session, url: login_path do |f| %>
	<div class="form-group">
	  <%= f.label :name %>
	  <%= f.text_field :name, placeholder: "Enter your name", class: "form-control" %>
	</div>
	<div class="form-group">
	  <%= f.label :password %>
	  <%= f.password_field :password, placeholder: "Enter your password",
	    class: "form-control" %>
	</div>
	<div class="text-center">
	  <%= f.submit "Login", class: "btn btn-info col-lg-12" %>
	</div>
	<div class="text-right">
	  <%= link_to "Register", new_user_path %>
	</div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.id %></td> 
  <td><%= user.name %></td> 
</tr>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 form-group">
      <label for="">Welcome <%= current_user.name %></label>
    </div>
    <div class="col-lg-12 form-group">
      <label>List Users</label>
      <table class="table">
        <thead>
          <th>ID</th>
          <th>User Name</th>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
    <%= link_to "Return", user_path(current_user) %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Register</h1>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter user name" %>
  </div>
  <div class="form-group">
    <%= f.label :password, "Password" %>
    <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter password confirmation" %>
  </div>
  <%= f.submit "Register", class: "btn btn-success" %><br/>
  <%= link_to "Login", login_path %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <label>User name: <%= @user.name %></label>
    </div>
    <div class="col-6">
      <%= link_to "Logout", logout_path, method: :delete %>
    </div>
  </div>
  <%= link_to "List Users", users_path %><br/>
  <a href="/">Home</a>
</div>